export const LocationList: string[] = [
  "Andhra Pradesh",
  "Assam",
  "Bihar",
  "Delhi",
  "Gujarat",
  "Haryana",
  "Karnataka",
  "Madhya Pradesh",
  "Maharashtra",
  "Punjab",
  "Rajasthan",
  "Telangana",
  "Uttar Pradesh",
  "West Bengal",
  "Other",
];

export const regionList: { name: string }[] = [
  { name: "Andhra Pradesh" },
  { name: "Assam" },
  { name: "Bihar" },
  { name: "Delhi" },
  { name: "Gujarat" },
  { name: "Haryana" },
  { name: "Karnataka" },
  { name: "Madhya Pradesh" },
  { name: "Maharashtra" },
  { name: "Punjab" },
  { name: "Rajasthan" },
  { name: "Telangana" },
  { name: "Uttar Pradesh" },
  { name: "West Bengal" },
  { name: "Other" },
];
